/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
        System.out.println(roll(9));
        System.out.println("======================================");

        int array[]={1,2,3,4,7,1};
        System.out.println(containsDuplicates(array));
        System.out.println("======================================");


        System.out.println(calculatingAverages(array));
        System.out.println("======================================");

        int[][] testingArray = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        System.out.println(Arrays.toString(arraysOfArrays(testingArray)));
    }

    //===============================================================
    public static ArrayList<Integer> roll(int number) {
        Random random = new Random();

        ArrayList<Integer> numbers = new ArrayList<>();
        for (int i = 0; i < number; i++) {
            int random_number = random.nextInt(6) + 1;
            numbers.add((random_number));

        }
        return numbers;
    }
    //=================================================================
    public static boolean containsDuplicates(int[] nums) {
        for (int i = 0; i < nums.length - 1; i++) {
            for (int j = i + 1; j < nums.length; j++) {
                if (nums[i] == nums[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    //===============================================================
    public static double calculatingAverages(int array[]) {
        double avg = 0;
        int arrayLength = array.length;
        for (int i = 0; i < arrayLength; i++) {
            avg += array[i];
        }
        return avg / arrayLength;
    }
    //================================================================
    public static int[] arraysOfArrays(int[][] array) {
        int minAvg = Integer.MAX_VALUE;
        int minIndex = -1;
        int avg;
        for (int i = 0; i < array.length; i++) {
            avg = 0;
            for (int j = 0; j < array[i].length; j++) {
                avg += array[i][j];
//                System.out.print(array[i][j] + " ");
            }
//            System.out.println("Array of " + i + " " + avg);
            if (avg < minAvg) {
                minAvg = avg;
                minIndex = i;
            }
//            System.out.println();
        }

        return array[minIndex];
    }
}