/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("AmmanRest", 4.1, 50);

        Review review1 = new Review("Great Food!", "Farah", 4.5, restaurant);
        restaurant.addReview(review1);

        Review review2 = new Review("Nicee", "Fofo", 3.0, restaurant);
        restaurant.addReview(review2);

        Review review3 = new Review("I like the food", "Fefe", 5.0, restaurant);
        restaurant.addReview(review3);

        System.out.println("Review 01: " + restaurant.numberOfStars);
        System.out.println("Review 02: " + restaurant.numberOfStars);
        System.out.println("Review 03: " + restaurant.numberOfStars);

        restaurant.addReview(review1);

        System.out.println(restaurant.toString());
        System.out.println(review3.toString());
        System.out.println("Last Rate Of Our Restaurant " + restaurant.numberOfStars);
    }
}
