/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("Farah Resteurant", 3, 50);
        Shop shop = new Shop("SubermarketFarah", "Fruait", 3);
        Theater theater = new Theater("Farah");

        theater.addMovie("One Piece");
        theater.addMovie("barbie");

        theater.removeMovie("barbie");

        Review review1 = new Review("test1", "nice food", 5, restaurant);
        Review review2 = new Review("test2", "Amazing food", 3, restaurant);
        Review review3 = new Review("test3", "good fruite", 4, shop);
        Review review4 = new Review("test4", "nice movie", 5, "One Piece", theater);
        Review review5 = new Review("test5", "nice movie", 4, theater);


        restaurant.addReview(review1);
        restaurant.addReview(review2);
        shop.addReview(review3);
        theater.addReview(review4);
        theater.addReview(review5);

        System.out.println(restaurant);
        System.out.println(shop);
        System.out.println(theater);

    }
}
