/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void testRestaurantToString()
    {
        Restaurant testDisplayRestaurant=new Restaurant("FarahRest",5,30);
        assertEquals("FarahRest, 5.0, 30.0$, 0",testDisplayRestaurant.toString());
    }
    @Test
    public void testReviewToString()
    {
        Restaurant testDisplayRestaurant=new Restaurant("FarahRest",5,30);
        Review testDisplayReview =new Review("Great Food!", "Farah", 4.5, testDisplayRestaurant);
        assertEquals("Great Food!, Farah, 4.5, FarahRest",testDisplayReview.toString());
    }
    @Test
    public void testAddReview() {
        Restaurant testDisplayRestaurant = new Restaurant("FarahRest", 5, 30);
        Review testDisplayReview1 = new Review("Great Food!", "Farah", 4.5, testDisplayRestaurant);
        Review testDisplayReview2 = new Review("Great Food!", "Farah", 4.5, testDisplayRestaurant);
        Review testDisplayReview3 = new Review("Great Food!", "Farah", 4.5, testDisplayRestaurant);
        testDisplayRestaurant.addReview(testDisplayReview1);
        testDisplayRestaurant.addReview(testDisplayReview2);
        testDisplayRestaurant.addReview(testDisplayReview3);
        assertEquals(4.5, testDisplayRestaurant.numberOfStars);
    }

}
